apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo
    stage: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp
      stage: test
  template:
    metadata:
      labels:
        app: todoapp
        stage: test
    spec:
      containers:
        - name: todo
          image: 277642653139.dkr.ecr.eu-central-1.amazonaws.com/todoapp:##VERSION##
          volumeMounts:
            - name: jwt-secret-vol
              mountPath: "/etc/secrets"
              readOnly: true
          env:
            - name: AWS_ACCESS_KEY_ID
              value: ##AWS_ACCESS_KEY_ID##
            - name: AWS_SECRET_ACCESS_KEY
              value: ##AWS_SECRET_ACCESS_KEY##
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todoapp
    stage: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer
