---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS for Todo App'

Resources:
  
  # This is the Role EKS needs in order to create the Resources for new K8S Clusters
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  # This is the role the K8S worker nodes need to talk to the control plane and to pull images from ecr etc.
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Path: /

  # creates the K8S control plane of the K8S cluster
  K8SCluster:
    Type: AWS::EKS::Cluster
    Properties:
        Name: todoapp
        Version: '1.16'
        RoleArn: !GetAtt EksServiceRole.Arn
        ResourcesVpcConfig:
          SubnetIds:
            - !ImportValue ToDoPublicSubnet01Export
            - !ImportValue ToDoPublicSubnet02Export
            - !ImportValue ToDoPrivateSubnet01Export
            - !ImportValue ToDoPrivateSubnet02Export

  # creates the worker nodes for the K8S cluster
  K8SClusterNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    DependsOn: K8SCluster
    Properties:
      ClusterName: todoapp
      NodeRole: !GetAtt NodeInstanceRole.Arn
      ScalingConfig:
        MinSize: 2
        DesiredSize: 3
        MaxSize: 3
      Labels:
        Type: EKS-Clusternode
        App: Todo-Webapp
      Subnets:
        - !ImportValue ToDoPrivateSubnet01Export
        - !ImportValue ToDoPrivateSubnet02Export

Outputs:

  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EksServiceRole.Arn
    Export:
      Name: ToDo-EksServiceRole-RoleArn

  NodeInstanceRole:
    Description: The node instance role
    Value: !GetAtt NodeInstanceRole.Arn
    Export:
      Name: ToDo-NodeInstanceRole-RoleArn