AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Project for the Capstone Assignment of the Udacity Cloud DevOps nanodegree.!And 

Resources:

  ToDoDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: TodoObjects
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "owner"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -  IndexName: TodoByUser
           KeySchema: 
             - AttributeName: "owner"
               KeyType: "HASH"
           Projection: 
             ProjectionType: ALL
  
  StaticResourcesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
        AccessControl: PublicRead
        BucketName: 'www.andrerieck.de'
        WebsiteConfiguration:
           IndexDocument: index.html
           ErrorDocument: index.html

  SampleBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref StaticResourcesBucket
      PolicyDocument: 
        Statement: 
           - 
            Action: 
               - "s3:GetObject"
            Effect: "Allow"
            Resource: 
               Fn::Join: 
                 - ""
                 - 
                   - "arn:aws:s3:::"
                   - !Ref StaticResourcesBucket
                   - "/*"
            Principal: "*"

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AutoVerifiedAttributes: 
        - email
      EmailVerificationMessage: "Please use the Verification Code {####} to verfiy you new Account."
      EmailVerificationSubject: "Welcome to ToDo-App. Verification of new Account."
      UserPoolName: UserPool4ToDoApplication

  ToDoAppUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: ToDoApplicationClient
      GenerateSecret: False
      UserPoolId: !Ref CognitoUserPool
